spring:
  application:
    name: news-collector

  datasource:
    url: jdbc:h2:mem:newsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 666784365079-v262okm8184ibqmckvfb49qgvb7gd6rr.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

server:
  port: 19093